# Generated by Django 5.1.1 on 2024-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_rating_reciperating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='rating',
            new_name='average_rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
