# Generated by Django 5.1.1 on 2024-10-07 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_foodphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 7, 11, 42, 38, 291118, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
